location = /API/openapi {
    include proxy.conf;
    proxy_pass http://$pyos_fqdn:$pyos_service_port/API/openapi;
}

# proxy requests to pyos
location /openapi {
    include proxy.conf;
    proxy_pass http://openapi;
}

