# HTTP/1.1 required for chunked transfer
proxy_http_version 1.1;
# Disable all buffering
proxy_buffering off;
proxy_cache off;
# No compression for event stream
gzip off;
# Headers
proxy_set_header Connection '';
# Long read timeout - 180 s
proxy_read_timeout 180s;
proxy_send_timeout 180s;
# Keep HTTP/1.1 chunked transfer encoding enabled for streams
chunked_transfer_encoding on;
# pass header to other client
proxy_pass_header X-Accel-Buffering;
