name: build route image

on:
  push:
  pull_request:

env:
    imagetag: "${{ github.event.client_payload.ref || github.ref_name }}"
    ref: "${{ github.event.client_payload.ref || github.ref_name }}"
      
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.imagename.outputs.image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          ref: ${{ env.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}
         
      - name: "image tag"
        run: echo "image tag set to '${{ env.imagetag }}'"

      - name: Build and push builder image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          build-args: |
            BASE_IMAGE_RELEASE=jammy
            BASE_IMAGE=abcdesktopio/openresty
          tags: |
            abcdesktopio/route:${{ env.imagetag }}

      - name: Output image name
        id: imagename 
        run: echo "::set-output name=image::abcdesktopio/route:${{ env.imagetag }}"
